### ISSUE TITLE
My number was blocked in whatsapp after 1 minutes after sending "signup"

### ISSUE THREAD

**Issue by maxmenGMK** [inUtil-info/node-red-contrib-whin#11]
I was try to get the token and sent message from whatsapp to number. But after 1 minutes from sending "signup" i was disconnected from whatsapp and now i cannot to connect to whatsapp at all. And all just i can see it just not a yellow lemon tree - i can see just message "your number was blocked, connect to support".
It seem like whatsapp dont like when somebody make nice services like this one.

**Comment by lu4t** [comment]
hi @maxmenGMK ,
if your number was blocked by whatsapp, I don't see any relation with sending a "signup" msg to whin... There are a bunch of numbers sending whatsapps to whin (included mine), and no issues at all. 
Look at whatsapp Terms of Use, there must be something you're doing that they don't like:
https://www.whatsapp.com/legal/terms-of-service#terms-of-service-acceptable-use-of-our-services

**Comment by maxmenGMK** [comment]
It is really something with terms of use of course. But the main thing is that there was no whatsapp on  this number before. I just register the new whatsapp account and the first message i sent from new created whatsapp account was the "signup" and there was no another messages at all neither before nor after. It seems like whatsapp blocking using services like this to make more money from "whatsapp business" and another marketing bullshit.

**Comment by lu4t** [comment]
Reading your comments, there's something that makes me feel like this is not the first number that you own that is banned from whatsapp.
I am no expert, and personally I have never been banned for abusing the TOU... I don't know what "whatsapp business" is, I cannot care less about the marketing stuff around whatsapp. Whin is not a service, it's just a free shared gateway for node-red Home Labs users... and it is not aimed to damage anyone's business.
But if this is really something that happened to you, it is worth knowing. Thanks for sharing!
