### ISSUE TITLE
Signup no response

### ISSUE THREAD

**Issue by hanung665** [inUtil-info/node-red-contrib-whin#12]
As subject, as per today, send signup text from +62xxx to +34613164997 but no reply after more than 3 hours.

**Comment by alsak0de** [comment]
Unfortunately, a version change on Whatsapp has taken us out of business for almost a day. We expect to have the platform back before end of today

**Comment by dougle03** [comment]
> We expect to have the platform back before end of today

Hiya, any joy?

**Comment by lu4t** [comment]
hi @dougle03 and @hanung665 it's all working again. 
Sorry for the time you had to wait, but we believe it will be for good... some MAJOR enhancements are about to be deployed after this upgrade.
Please check, and re-open the issue if you find any trouble.

**Comment by dougle03** [comment]
> Sorry for the time you had to wait

All working great for me. Thanks for working up a fix. Cheers
