### ISSUE TITLE
Whin receive message problem

### ISSUE THREAD

**Issue by firsttcrysis** [inUtil-info/node-red-contrib-whin#13]
I have issue that I can receive messages only when I sent messages from web.whatsapp.com. When I'm traying to send message from whasapp android app it doesn't work. I checked it on 2 different phone numbers and 2 different  smartphones - android 12 and updated whatsapp to newest one.
Whin send and confirm work without problem.

**Comment by lu4t** [comment]
Thanks for using whin!.

I guess you're talking about sending a whatsapp to your node-red env, from within the whatsapp android app.

To be all honest, we did not test that particular scenario cause we, the maintainers, are using iphones. 

I will try to get an Android phone and test if we can reproduce your problem... will get back with my comments shortly.

**Comment by firsttcrysis** [comment]
I really like Your project! Yes, I'm traying to send command from phone and node red is listening to whatsapp. Node red version 10.2.1.  
![image](https://user-images.githubusercontent.com/77902748/155200800-945e3d91-cfab-4b3c-91ab-56b4a632c149.png)
Simple flow - 1 and 2 are 2 different phones numbers.

**Comment by lu4t** [comment]
I did the testing with a borrowed android phone (xiaomi Redmi); added it to whin requesting a new token; adjusted the node-red nodes with its new configuration, and everything worked just fine.
I am affraid there must be something wrong on your end.

**Comment by lu4t** [comment]
> I really like Your project! Yes, I'm traying to send command from phone and node red is listening to whatsapp. Node red version 10.2.1. ![image](https://user-images.githubusercontent.com/77902748/155200800-945e3d91-cfab-4b3c-91ab-56b4a632c149.png) Simple flow - 1 and 2 are 2 different phones numbers.

weird config, but nevertheless it should work. Just make sure node 1 and 2 on your picture have the right config (it must be different on each).

These 2 nodes are listeners: this means that whatever you send to whin (using any whatsapp client) from number used on config 1, should pop on node 1. Same exact thing on phone with config 2.

Each number will have a different token, and are listening a different (encrypted) queue for reception.

**Comment by firsttcrysis** [comment]
Problem solved - I had beta version of Whatsapp. I removed it and changed on standard. Now is everything works! Thanks!

**Comment by lu4t** [comment]
> Problem solved - I had beta version of Whatsapp. I removed it and changed on standard. Now is everything works! Thanks!

Great!.
Running the beta version of whatsapp shoudn't be a problem neither, but anyway...
I guess you're using the node-red add-on for home assistant (node-red latest version is 2.X.X, not 10.X.X) We will be glad to know of use-cases when using whin on HA (it would be an inspiration for our youtube channel with samples and use-cases). Please share your ideas with the community, as we are not HA users :)
