### ISSUE TITLE
Whin just sends  "Hello [Signup]"

### ISSUE THREAD

**Issue by Maxklos** [inUtil-info/node-red-contrib-whin#14]
Whin was working great the last few Weeks. But today I recived again a "Hello" Message while at work. Back at Home i testet it: Every time I send something from Node Red i receive the "Hello, Please sign up" message (Screenshot at the end). When I signup again i just receive the same API Token again.  The problem occurs on both of my phones (different number and Token)

![Screenshot_20220226-195609](https://user-images.githubusercontent.com/17532916/155855795-dfbde71d-7ad8-48e3-a541-3a2426342fcc.png)

**Comment by alsak0de** [comment]
We had a set of unfortunate events. 
Everything should be ok now.
Thanks for letting us know.

**Comment by Maxklos** [comment]
Can confirm, everything works again after pressing [Signup]. Thank you very much

**Comment by lu4t** [comment]
> Can confirm, everything works again after pressing [Signup]. Thank you very much

Thanks!
