### ISSUE TITLE
SelfHosted.

### ISSUE THREAD

**Issue by Askeshine** [inUtil-info/node-red-contrib-whin#2]
Amazing App , any way for can selfhosted whatsapp nodejs ? u have guide for this ? thx.

**Comment by lu4t** [comment]
Hi, thanks for using whin!.
We are hosting the backend at a cloud provider, and have created no guide to selfhost it (yet). It would be very easy, though.
At the moment we are focused on developing the client side, working on several new features that are about to be delivered in the coming weeks.

**Comment by Askeshine** [comment]
Thx lu4t i see u are from spain im from argentina we can speak spanish !! i love ur your project but i need transfer host to argentina. I have bad internet.

**Comment by lu4t** [comment]
Hola @Askeshine, 
gracias por tus  palabras tan amables; como te decía no tenemos planes de documentar el backend, a corto plazo estamos centrados en nuevas funcionalidades del lado cliente que nos apetece hacer más, y son mas divertidas que documentar :)
Si hay alguna necesidad que detectes en el servicio, encantados de ayudarte.
Un saludo!
