### ISSUE TITLE
WHIN No working properly. No token received: March03th 08h48 GMT -6

### ISSUE THREAD

**Issue by Tr14rk** [inUtil-info/node-red-contrib-whin#21]
Hello, 

I was send a SIGNUP text to obtain the Token, and nothing happens! (from +52)

Can you check from you side if the service is Online?

**Comment by alsak0de** [comment]
would you mind trying again?
Everything seems to be working just fine
Please try and tell us if it worked, tx.

**Comment by Tr14rk** [comment]
> would you mind trying again? Everything seems to be working just fine Please try and tell us if it worked, tx.

Perfecto! Gracias.
Ya lo recibí.

Thank you! I was received the token right now.

**Comment by lu4t** [comment]
:+1:
