### ISSUE TITLE
Enviar mensajes a grupos

### ISSUE THREAD

**Issue by tomasdeltell** [inUtil-info/node-red-contrib-whin#22]
Sería posible poder enviar mensajes a un grupo donde esté Whin?

**Comment by lu4t** [comment]
Hola @tomasdeltell , esa funcionalidad está desactivada a propósito del gateway compartido, para proteger a los usuarios de posible spam. 
Pero hay mecanismos para conseguirlo: ¿qué es lo que quieres hacer?. Igual te podemos ayudar.
Un saludo

**Comment by tomasdeltell** [comment]
Hola. Tenía intención de usarlo para mandar las notificaciones de alertas de un grafana a un grupo de WhatsApp de mi empresa. Para tenerlo como apoyo a las notificaciones que ya tenemos por email o por slack.

**Comment by lu4t** [comment]
:)  
típico ejemplo por el que hemos capado a whin la función de mandar a grupos... se pretende evitar situaciones en las que el gw pueda ser "acusado" de mandar spam a gente que no desea recibir mensajes suyos.
El uso de whin requiere opt-in inicial por filosofía.
Hemos pensado un par de mecanismos para conseguir lo que tú pretendes, con un mecanismo pub/sub... pero aún estamos dándole vueltas a cuál sería la mejor opción.
Dejo abierto tu issue para que te enteres de cuándo está disponible.

**Comment by tomasdeltell** [comment]
De acuerdo, gracias

**Comment by tomasdeltell** [comment]
> :) típico ejemplo por el que hemos capado a whin la función de mandar a grupos... se pretende evitar situaciones en las que el gw pueda ser "acusado" de mandar spam a gente que no desea recibir mensajes suyos. El uso de whin requiere opt-in inicial por filosofía. Hemos pensado un par de mecanismos para conseguir lo que tú pretendes, con un mecanismo pub/sub... pero aún estamos dándole vueltas a cuál sería la mejor opción. Dejo abierto tu issue para que te enteres de cuándo está disponible.

Aunque en éste caso no se le podría acusar. Todos los miembros del grupo estarían de acuerdo en recibir las notificaciones, básicamente porque les interesa (es el departamento de IT de mi empresa) en lugar de estar pendientes del correo, por ejemplo. ¿No se podría hacer algo en éste caso?
Lo otro que se me ocurre, es mandar las notificaciones individualmente a cada miembro.

**Comment by lu4t** [comment]
> > :) típico ejemplo por el que hemos capado a whin la función de mandar a grupos... se pretende evitar situaciones en las que el gw pueda ser "acusado" de mandar spam a gente que no desea recibir mensajes suyos. El uso de whin requiere opt-in inicial por filosofía. Hemos pensado un par de mecanismos para conseguir lo que tú pretendes, con un mecanismo pub/sub... pero aún estamos dándole vueltas a cuál sería la mejor opción. Dejo abierto tu issue para que te enteres de cuándo está disponible.
> 
> Aunque en éste caso no se le podría acusar. Todos los miembros del grupo estarían de acuerdo en recibir las notificaciones, básicamente porque les interesa (es el departamento de IT de mi empresa) en lugar de estar pendientes del correo, por ejemplo. ¿No se podría hacer algo en éste caso? Lo otro que se me ocurre, es mandar las notificaciones individualmente a cada miembro.

como te decía: técnicamente no hay ningún problema. 
De hecho, es algo que hemos "capado" del código que está ejecutando el gw de whin, en los tenants privados que usamos para "nuestro consumo personal", los grupos están habilitados. 
La máxima es: aquel que quiera recibir un whatsapp de whin, primero tiene que escribirle. Sólo así nos aseguramos que nadie que no quiera reciba un whatsapp de whin. Para el caso que sugieres: nada impide que aquellos miembros de dpto IT que quieran, reciban las notificaciones que soliciten.
Un saludo!
