### ISSUE TITLE
Fallo al intentar enviar notificaciones desde Grafana

### ISSUE THREAD

**Issue by tomasdeltell** [inUtil-info/node-red-contrib-whin#23]
Estoy creando el webhook en grafana para enviar las notificaciones a whin. No se si creo mal el flujo o hago algo mal desde grafana, pero al intentar enviar un test, me da un error "Failed to send alert notifications". Adjunto el flujo y el webhook
![Screenshot_20220401_120913](https://user-images.githubusercontent.com/8511738/161243286-e2b089fb-4cd2-4f32-88fd-e9b3c85280fa.png)
![Screenshot_20220401_120934](https://user-images.githubusercontent.com/8511738/161243369-7a316463-ba64-479b-9f3d-622c9815635e.png)
¿Qué estoy haciendo mal?

**Comment by lu4t** [comment]
primero de todo: ¿qué versión de grafana usas?.

El video de ejemplo: https://youtu.be/GU-xY8jaa9A está grabado con versión 6. 

Las versiones posteriores de Grafana han variado su motor de alerting: https://grafana.com/docs/grafana/latest/alerting/old-alerting/ y puede que te quede algo pendiente de configurar...

**Comment by tomasdeltell** [comment]
Uso grafana 8.2.3

**Comment by tomasdeltell** [comment]
Vale, ni me había enterado de ésto, ya he habilitado las nuevas alertas y al hacer el test me da un 404 not found.

La url que uso es https://whin.inutil.info/hookin/TOKEN/TELEFONO

**Comment by lu4t** [comment]
> Vale, ni me había enterado de ésto, ya he habilitado las nuevas alertas y al hacer el test me da un 404 not found.
> 
> La url que uso es https://whin.inutil.info/hookin/TOKEN/TELEFONO

Ok, prueba a usar una url que incluya un path adicional (da igual lo que pongas). 
Ejemplo: https://whin.inutil.info/hookin/TOKEN/TELEFONO/lo-que-sea

Así te debería funcionar

**Comment by tomasdeltell** [comment]
Vale, ahora sí. Gracias!

**Comment by lu4t** [comment]
> Vale, ahora sí. Gracias!

si me pasas una guia donde se configuren las alertas de grafana 8+ actualizo el video... la versión que nosotros usamos es antigua y no sé cómo va el módulo de alerting nuevo....
