### ISSUE TITLE
Mqtt error - help

### ISSUE THREAD

**Issue by filiperigueira** [inUtil-info/node-red-contrib-whin#24]
Instal the pallet, works fine to send message! But for receive messages and confirmation appear the error:

Error: Cannot find module 'mqtt'
Require stack:
- C:\Users\8350\.node-red\node_modules\node-red-contrib-whin\whin.js
- C:\Users\8350\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\loader.js
- C:\Users\8350\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\index.js
- C:\Users\8350\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\index.js
- C:\Users\8350\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\index.js
- C:\Users\8350\AppData\Roaming\npm\node_modules\node-red\lib\red.js
- C:\Users\8350\AppData\Roaming\npm\node_modules\node-red\red.jsError: Cannot find module 'mqtt'
- 

can you help me?

**Comment by lu4t** [comment]
the error shows you don't have mqtt.js library installed. It's a default module on node-red.

Try doing:  `npm install mqtt --save`  from within your nodo_modules folder, before starting node-red.

If it doesn't work, let me know if you see mqtt nodes on the node-red editor.

**Comment by filiperigueira** [comment]
Works Fine! Many Thanks!
