### ISSUE TITLE
Ser numero móvil remitente del mensaje.

### ISSUE THREAD

**Issue by EnzoRimapa** [inUtil-info/node-red-contrib-whin#25]
Hola buenas tardes, quería saber si hay la posibilidad de que se nos permita ser el número remitente del mensaje de whatsapp a un destinatario cuyo numero esté agregado en el código con la finalidad de continuar ambos la comunicación desde el chat de la aplicación.
Muchas gracias.

**Comment by lu4t** [comment]
hola @EnzoRimapa, si quieres tú remitir el whatsapp, ¿para qué necesitas usar una pasarela compartida?
Perdoname, pero no sé si entiendo tu pregunta.  :)

**Comment by EnzoRimapa** [comment]
Hola @lu4t gracias por tu respuesta si lo hice la pregunta antes de averiguar el repositorio de Baileys con ello ya podré resolver lo que necesitaba pero se me hace un poco difícil arrancarlo o montarlo y verlo en funcionamiento con algunas de las funciones que tiene, seria bueno ello.. hay algún tutorial en video?
Un saludo!

**Comment by lu4t** [comment]
Hola, no conozco ningún video tutorial de ese repo. 
Un saludo!
