### ISSUE TITLE
mi propio gateway

### ISSUE THREAD

**Issue by ixdos** [inUtil-info/node-red-contrib-whin#26]
Me gustaria usar whim para conectar whatsapp a otras aplicaciones y asi tener poder escribir mensajes y si es posible mandar fotos de whatsapp a telegram por ejemplo.
Ya he leido que whim no permite el uso de grupos. Seria posible usarlo en grupos con mi propio gateway? Como podria hacerlo?

**Comment by lu4t** [comment]
hola, la verdad es que no se me ocurre otra opción que hacer tu propio gw.
Un saludo!
