### ISSUE TITLE
mqin.inutil.info not resolving

### ISSUE THREAD

**Issue by kickouille** [inUtil-info/node-red-contrib-whin#27]
Hello,

I installed latest 0.1.13 version from the Palette. Generating the key works fine as well as sending messages.
However the receiver stays disconnected, and after checking the source code, I realized that the MQTT/WSS the node is trying to connect to (mqin.inutil.info) is not being resolved by DNS:

nslookup mqin.inutil.info
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find mqin.inutil.info: NXDOMAIN

Is that an issue or has the service been abandoned, which makes this node deprecated?

Regards,

Kickouille

**Comment by Seba200086** [comment]
Same story here... whin-receive node stays "disconnected"...
Btw, whin-confirm node is not working neither.

**Comment by luisfpadovani** [comment]
Same story here to... whin-receive node stays "disconnected"...
Btw, whin-confirm node is not working neither.

**Comment by MiMoertel** [comment]
Same story here to... whin-receive node stays "disconnected"...
Btw, whin-confirm node is not working neither.

**Comment by lu4t** [comment]
@MiMoertel , @luisfpadovani , @kickouille , @Seba200086 
can you please check if it works for you now?. We had an issue on the cluster last May 2nd, it was a local holiday, and we did not notice it till the next day. 
BTW: next time, you can check if any service is failing here: https://status.inutil.info/

(if you have any issue, pls reopen the issue).

**Comment by Seba200086** [comment]
@lu4t I need to report that whin-receive node still have status "disconnected"
![obraz](https://user-images.githubusercontent.com/60579173/166971977-124ca091-fa37-46aa-ac2f-a64cddac7cc2.png)

**Comment by lu4t** [comment]
I'll have a look. Thx!

**Comment by lu4t** [comment]
we need to work on this @Seba200086 
You're right, the broker is dropping connections; essentially there're too many people connected and the CPU is exhausted. For some users it is working though.
When we tweak the config I will close the issue to let you know :)

**Comment by Seba200086** [comment]
OK, great. Thank you in advance!

**Comment by lu4t** [comment]
update to node-red-contrib-whin 1.14 and it should work now 
![image](https://user-images.githubusercontent.com/29571529/167030586-6deff97d-1b03-449e-81a0-322b6372a76f.png)

**Comment by luisfpadovani** [comment]
Thank @lu4t
