### ISSUE TITLE
[Feature request] Ability to reset the whin-confirm node

### ISSUE THREAD

**Issue by Seba200086** [inUtil-info/node-red-contrib-whin#28]
In some scenarios, it would be desirable to be able to reset the whin-confirm node.

E.g. light on -> wait 2h -> question "Do I turn off the light?" (ttl 1h)
If in the meantime the light is turned off with a physical switch then I would like the node to be reset (stop awaiting response), as the question is not valid any more.

The reset could occur after the msg.reset (true) is received.

Could such an enhancement be implemented?

**Comment by lu4t** [comment]
Whin-confirm main use case is to confirm on whatsapp something happening. In your example, you're using ttl field as a timer... You have great alternatives for that use case, I would not use whin for that. 
TTL is just the time you have to answer the whatsapp with the question, the TTL set (and time remaining) lives on our backend, and our backend provides the back-channel to your whatsapp number. We don't know (and don't want to) anything of your local environment and the events triggered there.
Back to your example, whin-confirm would fit on it like this: if the light is turned off with a physical switch (assuming the switch and/or the lightbulb are "smart") you could receive a whatsapp to confirm that you want to "allow" this event to happen....

**Comment by Seba200086** [comment]
I am afraid that I have not been well understood.

In my example, I was referring to a situation in which:
We turn on the light e.g. in the office (by "smart" switch) -> wait 2h (trigger node) -> Question "The light in the office is on, turn it off?" (with ttl = 2h, we give time to read and respond...)

If the light is turned off in the meantime with a physical smart switch then the node is still waiting for a response anyway.

If we send a query through another whin-confirm node while waiting for a response on first one the response will affect both.

The inability to reset will lead to a situation where several nodes may be in a waiting state and lead to unexpected actions.

I would like to kindly repeat my request to able reset a whin-confim node, similar to a standard trigger node:
![obraz](https://user-images.githubusercontent.com/60579173/167289136-fff5b049-d020-4770-9870-4b5f669242eb.png)


Thank you in advance!
