### ISSUE TITLE
I sent more than 20 messages

### ISSUE THREAD

**Issue by diegogodoy06** [inUtil-info/node-red-contrib-whin#29]
I just installed the new function.  I was testing inside the nodered, by accident I ended up passing 20 messages within 1h.  What to do now?

**Comment by lu4t** [comment]
Do not worry, if you reach the hard-limit you just need to wait 60 mins and the counters will be reset. :)

**Comment by diegogodoy06** [comment]
I think there was some bug with my number, it's not listening to messages.  I tested with another number and it is working normally.  Also I'm not getting the code when sending signup

**Comment by diegogodoy06** [comment]
he just doesn't listen.  but send messages normally

**Comment by lu4t** [comment]
Hi @diegogodoy06, if you send "signup" you should get a new token as response. 
Tell me the last 5 numbers of your cell, and I will remove if manually (if the token exits).

**Comment by diegogodoy06** [comment]
Ok
981342702

**Comment by lu4t** [comment]
> Ok 981342702

ok, deleted... try and check if it works now

**Comment by diegogodoy06** [comment]
I managed to get the token again.  but he is still not listening on nodered

**Comment by lu4t** [comment]
when you say listening you mean receiving whatsapps on node-red?... if this is the case, make sure you're using the last release of whin node. We did some changes on the way msgs are pushed from Whatsapp to NR.

**Comment by diegogodoy06** [comment]
Exactly what I meant.  messages do not arrive on nodered.  node is up to date and other numbers work normally

**Comment by lu4t** [comment]
> Exactly what I meant. messages do not arrive on nodered. node is up to date and other numbers work normally

I don't believe there's much more we can do to help... sounds like something is not working on your side... try removing and installing whin again on your node-red (don't forget removing the config node and restarting node-red after).
