### ISSUE TITLE
Error con update.

### ISSUE THREAD

**Issue by Askeshine** [inUtil-info/node-red-contrib-whin#3]
Hola luego de actualizar me tira esto cuando uso el nuevo nodo de recepcion de mensajes.

```
Error: Cannot find module 'mqtt'
Require stack:
- /home/pi/.node-red/node_modules/node-red-contrib-whin/whin.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
```

**Comment by lu4t** [comment]
Hi @Askeshine,
I will answer in english so that the rest of the whin community can take advantage of the comments.
This update is adding two new nodes, as described on the read.me 
It has no breaking changes, but we rebuilt the project so that all the nodes fit into one single package. Depending on which is the version you were using before the upgrade, you might find a problem we did not catch on our tests.

My suggestion is:
1.- remove whin completely from the node-red (**do not forget to remove also the whin-config node**).
2.- re-start nodered
3.- make a clean install from the palette.
4.- re-start nodered
5.- complete the config filling in the fields on the config node. You don't need to copy your token, just click here: https://wa.me/34613164997?text=signup and you will get it again.

I hope it helps; if you still have problems, just let us know.

**Comment by Askeshine** [comment]
Ok, 

i do all things and keep showing that error. only with this 
![imagen](https://user-images.githubusercontent.com/37356127/148755117-fcf3c0fd-3d61-4ac8-a472-528f2f28ce48.png)

**Comment by lu4t** [comment]
You have to uninstall whin first, then follow the process explained above.

Probably, you still have some nodes in the existing flows, or configuration nodes. Check in the menu Configuration Nodes for any unused nodes and delete them, then deploy changes.

When you're sure there's no remaining whin nodes on the flows, AND there's no config node remaining:

1.- Log-in to the nodered terminal.
2.- cd to .node-red folder (usually mapped to /data if you're using docker).
3.- Using package manager from the command line, from within your .node-red folder -this is important-, run
npm uninstall node-red-contrib-whin
4.- If this doesn't remove whin, then post the full output from the command here.

**Comment by Askeshine** [comment]
> You have to uninstall whin first, then follow the process explained above.
> 
> Probably, you still have some nodes in the existing flows, or configuration nodes. Check in the menu Configuration Nodes for any unused nodes and delete them, then deploy changes.
> 
> When you're sure there's no remaining whin nodes on the flows, AND there's no config node remaining:
> 
> 1.- Log-in to the nodered terminal. 2.- cd to .node-red folder (usually mapped to /data if you're using docker). 3.- Using package manager from the command line, from within your .node-red folder -this is important-, run npm uninstall node-red-contrib-whin 4.- If this doesn't remove whin, then post the full output from the command here.


Same error.
```
Error: Cannot find module 'mqtt'
Require stack:
- /home/pi/.node-red/node_modules/node-red-contrib-whin/whin.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
```

![imagen](https://user-images.githubusercontent.com/37356127/148940854-1410cffa-09f0-46e2-be8e-c8ff0b57c52b.png)

![imagen](https://user-images.githubusercontent.com/37356127/148940897-090ec111-8036-41db-82cb-095083602cf3.png)

**Comment by lu4t** [comment]
okay, so it looks like you've updated to the latest version of whin (0.1.4) correctly.

Now it seems like you're missing a node-red core node, in particular: mqtt - which is declared as dependency.

Can you please check if you find a folder called mqtt at /usr/lib/node-modules/node-red/node_modules ?

This path has nothing to do with contrib-whin, but the core node-red modules. If you cannot find mqtt there, then you must install it before enabling whin.

**Comment by Askeshine** [comment]
I use mqtt in my node red, I have 8 esp8266 connected all sends updates with mqtt

Sent with a Spark

**Comment by lu4t** [comment]
lo siento @Askeshine, me temo que me he quedado sin ideas de qué puede estar pasando... veo que has acutalizado a la última versión del nodo whin, entiendo que debe ser algo local a tu RPi porque vemos que el resto de usuarios están funcionando con normalidad.

**Comment by moshed** [comment]
I am having the same issue. getting error 
```
Error: Cannot find module 'mqtt'
Require stack:
- /home/pi/.node-red/node_modules/node-red-contrib-whin/whin.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/local/lib/node_modules/node-red/lib/red.js
- /usr/local/lib/node_modules/node-red/red.js
```

I have done the steps mentioned here https://github.com/inUtil-info/node-red-contrib-whin/issues/3#issuecomment-1008718917 and checked the path mentioned here https://github.com/inUtil-info/node-red-contrib-whin/issues/3#issuecomment-1010085900 and I do not have MQTT folder there but I do have it in /usr/local/lib/node_modules/node-red/node_modules/mqtt

**Comment by lu4t** [comment]
looks like the RPi installer maps the node_modules folder outside the Dockerfile PATH

**Comment by lu4t** [comment]
> I am having the same issue. getting error
> 
> ```
> Error: Cannot find module 'mqtt'
> Require stack:
> - /home/pi/.node-red/node_modules/node-red-contrib-whin/whin.js
> - /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
> - /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
> - /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
> - /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
> - /usr/local/lib/node_modules/node-red/lib/red.js
> - /usr/local/lib/node_modules/node-red/red.js
> ```
> 
> I have done the steps mentioned here [#3 (comment)](https://github.com/inUtil-info/node-red-contrib-whin/issues/3#issuecomment-1008718917) and checked the path mentioned here [#3 (comment)](https://github.com/inUtil-info/node-red-contrib-whin/issues/3#issuecomment-1010085900) and I do not have MQTT folder there but I do have it in /usr/local/lib/node_modules/node-red/node_modules/mqtt

Are you running nodered on RPi raspbian? or is it running as a docker container on the RPi?
the PATHs you get on the logs attached are weird.

**Comment by moshed** [comment]
yes that is exactly correct I am running node-red on a pi4 with raspbian

**Comment by lu4t** [comment]
Hi @moshed, I am afraid that the problem has to do with the way nodered is installed on the RPi. We are not running whin on a RPi and cannot troubleshoot the install process.
I had a look at this: http://stevesnoderedguide.com/installing-node-red and I guess you probably need to adjust the settings.js to your needs.
BR

**Comment by moshed** [comment]
ok thanks! I will take a look at that and see if I can manage it.
