### ISSUE TITLE
messages from phone won't get to Node Red 

### ISSUE THREAD

**Issue by HomePLayer1971** [inUtil-info/node-red-contrib-whin#30]
sending from web.whatsapp works,

a replay from a whin-confirms works

latest version of whin
https://discourse.nodered.org/t/whatsapp-notifications-node/55534/48?u=homeplayer

ALL WORKING NOW.
after a uninstall / install of whatsapp, keeping the date on the phone, same problem
after a uninstall / install of whatsapp DELETING 1.2Gb of data its working now

**Comment by lu4t** [comment]
Which version of whatsapp have you on your cell?... 
if your phone is very old, or if you have not updated whatsapp app on it for a long long time, we might be filtering messages on the backend.

**Comment by HomePLayer1971** [comment]
Version 2.22.11.82
OnePlus 6
Android 11
OxygenOS 11.1.2.2
Kernel 4.9.227-perf+

**Comment by lu4t** [comment]
It's weird, the delivery process from whatsapp ----> node-red is the same, no matter which is the user-agent you use...
when you say: "a reply for whin-confirm works"... do you mean replying from the WA app on your phone?, or replying from the whatsapp-web client?, or both?

**Comment by HomePLayer1971** [comment]
That just works like a charm, both

Just a msg from phone will not come in

**Comment by lu4t** [comment]
whin-confirm and whin-receive share the exact same code when it comes to receiving a message from Whatsapp into node-red.
Whin-confirm just receives a YES or NO message payload, while whin-receive is able to receive any string. But the protocol, and back-end is the same.
The only thing I could suggest you is removing and installing contrib-whin package again, making sure the config node is also removed...  re-start node-red, then install whin again and config it... re-start node-red after, and try if it works.

As I said before, we are aware of bugs on older versions of whatsapp app on old terminals, or even people who is still not using the multidevice version of whatsapp. But in all these cases, they will not be able to receive a message at all; in other words both nodes: receive and confirm will fail. In your case, I am affraid I am not able to find a root-cause to help you. Sorry man.

**Comment by Seba200086** [comment]
Same problem here...

I can send from node red -> whin -> whatsapp
I cannot receive anything in node red (whatsapp -> whin -> node red)...

![obraz](https://user-images.githubusercontent.com/60579173/171872861-adb5238b-d266-44ad-b91e-417fb23d73d3.png)

It says that it is listening, but it does not working...

**Comment by lu4t** [comment]
@Seba200086 can you please let me know which version of contrib-whin are you running?, is whin-confirm working for you?

**Comment by HomePLayer1971** [comment]
Whin-confirm works and that is what is puzzelring me, also [web whatapp](https://web.whatsapp.com/) --> node red works

clean install DietPi install Node Red pallet install Whin,
same problem. Now I will do the same whit a clean install of RaspbianOS, will report later

**Comment by Seba200086** [comment]
> @Seba200086 can you please let me know which version of contrib-whin are you running?, is whin-confirm working for you?

0.1.14 (latest). Whatsapp on android (latest).
It is working now again.

**Comment by HomePLayer1971** [comment]
Raspberry Pi Imager -- RaspberryOS 64bit lite on a 16Gb Ssd **(second Pi)**
hostname test 
user lol

lol@test:~ $ history
    1  sudo apt update && sudo apt full-upgrade
    2  sudo reboot
    3  bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)

node-red -- pallet install Whin
Whin-send Works
add Whin-receive -- Error.

5 Jun 09:55:41 - [info] Starting flows
5 Jun 09:55:41 - [error] [whin-receive:f0dc589a77bb2aa8] Error: Cannot find module 'mqtt'
Require stack:
- /home/lol/.node-red/node_modules/node-red-contrib-whin/whin.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

same error whit a clean install whit user 'pi'


mqtt is present in the pallet
using mqtt node, 
server - mqin.inutil.info poort 30540
Client ID - whin-client
Topic - whin/ + token

from a other Pi sending a whin-confirm
the yes/no from a msg whin-confirm will arrive encrypted, on the newly installed RaspianOS second Pi 
both a text from android phone not

**Comment by lu4t** [comment]
> Raspberry Pi Imager -- RaspberryOS 64bit lite on a 16Gb Ssd **(second Pi)** hostname test user lol
> 
> lol@test:~ $ history 1 sudo apt update && sudo apt full-upgrade 2 sudo reboot 3 bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
> 
> node-red -- pallet install Whin Whin-send Works add Whin-receive -- Error.
> 
> 5 Jun 09:55:41 - [info] Starting flows 5 Jun 09:55:41 - [error] [whin-receive:f0dc589a77bb2aa8] Error: Cannot find module 'mqtt' Require stack:
> 
>     * /home/lol/.node-red/node_modules/node-red-contrib-whin/whin.js
> 
>     * /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
> 
>     * /usr/lib/node_modules/node-red/node_modulthees/@node-red/registry/lib/index.js
> 
>     * /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
> 
>     * /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
> 
>     * /usr/lib/node_modules/node-red/lib/red.js
> 
>     * /usr/lib/node_modules/node-red/red.js
> 
> 
> same error whit a clean install whit user 'pi'
> 
> mqtt is present in the pallet using mqtt node, server - mqin.inutil.info poort 30540 Client ID - whin-client Topic - whin/ + token
> 
> from a other Pi sending a whin-confirm the yes/no from a msg whin-confirm will arrive encrypted, on the newly installed RaspianOS second Pi both a text from android phone not

mqtt.js is required by whin-receive and whin-confirm, try installing this module on the right path. 
If you're able to see the encrypted version of the messages sent from whatsapp to node-red, the only thing you're missing is using  whin token. What these two modules do is use the token to un-encrypt the delivered message.

**Comment by HomePLayer1971** [comment]
Darn,
I really don't know what's going on, why it aint working for me.
fact's;
token is correct
whin-send works
whin-confirm works
msg from web.whatsapp.com works
msg from up-to-date oneplus 6 will NOT work

Took a Old oneplus 5t dusted it off, installed whatsapp MAN it is working.
now we know it is the phone still lost what it could be

**Comment by HomePLayer1971** [comment]
ALL WORKING NOW.
after a uninstall / install of whatsapp, keeping the date on the phone, same problem
after a uninstall / install of whatsapp DELETING 1.2Gb of data its working now

thanks for the help and the node Whin

**Comment by lu4t** [comment]
On some phones, the WhatsApp app adds metadata that are filtered out at the bridge. In other words: there're several messages formats, when sending plain messages your phone is using a different format than the one it is using when answering the yes/no question of whin-confirm WhatsApp template.
From time to time we review the payload format and add new fields.

**Comment by lu4t** [comment]
> ALL WORKING NOW. after a uninstall / install of whatsapp, keeping the date on the phone, same problem after a uninstall / install of whatsapp DELETING 1.2Gb of data its working now
> 
> thanks for the help and the node Whin

:)
