### ISSUE TITLE
Formato de numero de telefone no Brasil

### ISSUE THREAD

**Issue by Vidal1001** [inUtil-info/node-red-contrib-whin#31]
A algum tempo foi adicionado um 9 aos números de telefone no Brasil, meu telefone é 98138xxxx (os x pra não passar meu numero aqui kkk), a integração só funciona se eu colocar sem o 9, exemplo 8138xxxx, que é o formato antigo, porém o whin-receive não me mostra nada nem de um jeito nem de outro,  o whin-send funciona normalmente, sem o 9 claro,  e o whin-confirm também, inclusive ao responder a pergunta do whin-confirm ela aparece no whin-receive, enfim creio possa ser algo com essa mudança de número de telefones pois com um numero a mais pode ser que a aplicação se perca, não sei, mas caso tenha resposta pra meu problema por favor responda pois quero muito usar essa integração no meu node-red, grato pela ajuda!

**Comment by lu4t** [comment]
Hi,
I am affraid the problem you have has nothing to do with the format change. we indeed have many ppl from brasil using whin, and they've no reported any problem at all.
In fact, the numbers used are those from whatsapp (and they really don't care of any local change happening).
I recommend you make sure you're using the latest version, or un-install and install whin from scratch.
