### ISSUE TITLE
Not responding to sent messages or signup requests

### ISSUE THREAD

**Issue by dougle03** [inUtil-info/node-red-contrib-whin#34]
Hi,
System seems to be down today. No messages since yesterday and no response to 'signup' message. Single tick, not delivered.
Is it my end or is there a problem?
Thanks

**Comment by lu4t** [comment]
Yes, you're right, system is down... We're doing a major update on the code and will probably come back over the weekend...

It's our fault , we did not say a word in advance, but it's our policy not to get in touch with any of the users... :) 

You can check de status here:
https://status.inutil.info/


I will close the issue when the service is back.

**Comment by dougle03** [comment]
Thanks for the update. Cheers

**Comment by lu4t** [comment]
system is up again, migration completed :)
