### ISSUE TITLE
Problem with payload

### ISSUE THREAD

**Issue by VinicioAM** [inUtil-info/node-red-contrib-whin#35]
Hello. Im in trouble to send my payload to whatsapp. 

As you can see in printscreen, im sending the payload to whatsapp and debug.. it is working well, the message is delivered ok in debug. 

![image](https://user-images.githubusercontent.com/109367504/179270838-225dbb7b-62dd-46a2-9b4e-20a28bdf95c1.jpeg)

Here is my whin config:

![image](https://user-images.githubusercontent.com/109367504/179271262-90b7b11e-c1d5-41db-acc4-eedec2754f52.jpeg)

And the only result I get in whatsapp is:

 ![image](https://user-images.githubusercontent.com/109367504/179271348-5913e3c3-06b6-4be8-9492-14f3bb6bb914.jpeg)

Which is not correct (this is not the payload). 

Any ideia about this problem?! 

Thanks

**Comment by lu4t** [comment]
What you're sending is a json object, that's why you get what you get on whatsapp. This is not a problem at all.

Read FAQ #5 for details:
https://github.com/inUtil-info/node-red-contrib-whin/wiki/FAQ


I suggest you use the examples on the repo to learn how to use whin.
