### ISSUE TITLE
Issue with whin-recieve and whin-send using different number

### ISSUE THREAD

**Issue by FcoDev8** [inUtil-info/node-red-contrib-whin#36]
Hi there, first of all i want to thank you for developing whin, it is indeed very useful. I have been testing the recieve node without success since Saturday afternoon. I tested whin-send today by triggering my flow from inside node red and recieved a response but from a different number. I wanted to know if there is an issue/update regarding whin or is it just temporary. Thanks in advance.

**Comment by lu4t** [comment]
Hi, thanks for your feedback.

You're right, we (me and @alsak0de) did some changes over the weekend and the consequences are:
1- whin is currently not accepting new users (only existing users will be able to use the service -for some days-).
2- messages are delivered from node-red to whatsapp from a different number. (not the one used for sign up).

Whin will get "back to normal" probably next the weekend. 

I will leave this issue open till we complete this changes.  :)

**Comment by alsak0de** [comment]
Everything should be back to normal. Please re-open otherwise.

**Comment by FcoDev8** [comment]
Everithing is ok now, thank you very much.
