### ISSUE TITLE
Error whin-confirm y whin-receive

### ISSUE THREAD

**Issue by Alonsjor** [inUtil-info/node-red-contrib-whin#38]
Hola,
 
antes de nada agredecer vuestro software y servicio. Es genial. En mi caso estoy utilizando una Raspberry PI 3 B con Node Red . He instalado whin y whin-send funciona correctamente . Desafortunadamente whin-confirm y whin-receive no funcionan ( no recibo el mesaje en Node Red). Creo que debe ser porque cuando hago un deploy me sale siempre el siguiente error :

Error: Cannot find module 'mqtt'
Require stack:
- /home/ubuntu/.node-red/node_modules/node-red-contrib-whin/whin.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

Podeis ayudarme a corregir el problema.

 Si la cosa es complicada lo pasaré a un colega*  experto en Ubuntu y Java. Si es facil lo hare yo mismo . Muchas gracias. 

*P.D. el colega es mi hijo 

Saludos

**Comment by lu4t** [comment]
hola, el error aparece porque te falta una de las dependencias: mqtt.js esto es raro porque forma parte de los modulos del core de node-red
prueba a borrar y reinstalar whin... y si sigue sin funcionar, mira este otro issue: https://github.com/inUtil-info/node-red-contrib-whin/issues/24

**Comment by Alonsjor** [comment]
Gracias, por tu respuesta. He probado borrando y reinstalando whin, pero aparece el mismo error. Tengo pendiente ejecutar la solución propuesta en issue:#24. Cuando pueda probarlo respondo en este mismo hilo.

Saludos

**Comment by Alonsjor** [comment]
Hola, ya puedo recibir mensajes. El problema parece ser que estaba en un error ( en el arranque de la tarjeta mini SD). 
Aun no puedo confirmar . Da el siguiente error : Whin Error: Could not connect to WHIN backend

Gracias
