### ISSUE TITLE
Messages sent by another number

### ISSUE THREAD

**Issue by ikeserpa** [inUtil-info/node-red-contrib-whin#39]
Hello, thank you very much for your free service Whin, I greatly appreciate your usefulness. In the last few days I have received messages from Whin from another phone number: +34 605 797764 instead of +34 605 164997. I would like to know if I am doing something wrong on my side, or if it is a characteristic of the service itself. Some time ago the same thing happened, but it normalized after a few days. Thank you very much!

**Comment by lu4t** [comment]
Hi, the whin free gateway is using always the same number.
However, when we do some test, roll out new features, or perform system upgrades, sometimes we switch to a different number to avoid msg delivery disruptions to the community... but this is not always the case, we switch numbers when we believe it is going to take us more than an hour or so to complete our testings.
The numbers you include on your question are both from whin, so don't worry. If you don't wish to receive whatsapps from a different number, you always can block the number on whatsapp :)
