### ISSUE TITLE
Does not work anymore.

### ISSUE THREAD

**Issue by peterossege** [inUtil-info/node-red-contrib-whin#42]
I already signed up a few months ago, it worked perfectly. Since a few weeks I can't receive any messages and I always get:

To use WHIN, you must first sign up to get your service token by sending the word signup.

When I send "signup" I get the same message.

**Comment by lu4t** [comment]
Hi,
can you please tell the last five or six numbers of your whatsapp number? 
Maybe your expired token is cached somewhere... we'll have a look at it.

**Comment by peterossege** [comment]
Hi, yes I can, it is 49......48914

**Comment by lu4t** [comment]
This is related to #41 https://github.com/inUtil-info/node-red-contrib-whin/issues/41

You activated the ephemeralSetting on Whatsapp, and this is why you're not getting the signup msg processed.

You can wait till we solve this known issue, or turn off the setting.

I will leave this issue open till we complete the changes needed on the backend.

regards

**Comment by lu4t** [comment]
@peterossege Can you please check if it works now?

**Comment by peterossege** [comment]
It works! Thank you!

**Comment by lu4t** [comment]
good to know.
