### ISSUE TITLE
Whin-confirm don't send message to whatsapp

### ISSUE THREAD

**Issue by ikeserpa** [inUtil-info/node-red-contrib-whin#43]
Hello friends, thank you very much for your work. When I trigger the whi-confirm node, I don't get anything on whatsapp. The other whi-send and whi-receive nodes work perfectly. Could you shed some light on what I might be doing incorrectly? Thank you very much.

**Comment by lu4t** [comment]
the whin-confirm node will be renewed. The legacy version you're using does have problems that are related to how the old back-end works. 
Stay tunned for the new release of whin.
