### ISSUE TITLE
Receiving multiple messages sent at once!!

### ISSUE THREAD

**Issue by ryangonzalez133** [inUtil-info/node-red-contrib-whin#44]
Hi, I really like your work. 
In the last few days I don't know what's been going on, but sometimes when I send a single message, whi - send returns me with multiple repeated messages. When trying to correct it thinking it could be one of my functions, it ended up that when I sent another message to the test, the whi-send returned more than 40 messages at the same time, this ended up causing my ip and number to be blocked. I would like to be analyzed the possibility of removing my number from the blocked list please, I would be very grateful. Thanks for all your contribution.
Any new information just ask what I'm willing to inform.

**Comment by ryangonzalez133** [comment]
The fact happens in a random way, being able to work without arriving multiple messages, as it can simply arrive several messages. Because of what happened, I couldn't figure out if the event was coming from my job or somewhere else.

**Comment by lu4t** [comment]
this must me related with your code.
